const defaultExerciseTypes = [
    {
      name: "Rowing bucheron",
      advice: "1 min gauche puis 1 min droite",
      timer: 60,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Développé incliné - Barre",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 150,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Leg Extension",
      advice: '30" de chaque avec Leg Curl',
      timer: 30,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Développé couché - Haltères",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 120,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Fentes Bulgare - Haltères",
      advice: "",
      timer: 90,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Tractions lestées",
      advice: "Top set puis 10% du poids à chaque série",
      timer: 120,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Élévation frontale - Poulie vis-à-vis",
      advice: 'Pic de contraction 2" en haut',
      timer: 90,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Romanian Deadlift - Haltères",
      advice: "",
      timer: 90,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Fentes - Barre",
      advice: "",
      timer: 90,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Fentes - Haltères",
      advice: "",
      timer: 90,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Développé couché - Barre",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 120,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Tractions Neutres",
      advice: "Tirer avec les bras, pas avec le dos",
      timer: 90,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Face Pull - Poulie Haute",
      advice: "",
      timer: 60,
      repRange1: "15-20",
      repRange2: "15-20",
      repRange3: "15-20",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Face Pull - Rotation",
      advice: "",
      timer: 60,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Développé incliné - Haltères",
      advice: "Top set puis 10% du poids à chaque série",
      timer: 150,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Curl Incliné - Barre EZ",
      advice: "",
      timer: 90,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Élévation latérales - Haltères",
      advice:
        "Raptor Set: Dernière série en dégressive mécanique -> Upright Row",
      timer: 60,
      repRange1: "15-20",
      repRange2: "10-15",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Dead Lift - Trap Bar",
      advice: "",
      timer: 120,
      repRange1: "6-10",
      repRange2: "6-10",
      repRange3: "6-10",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Mollets - Barre Guidée",
      advice: "Tempo 1-2-2-1",
      timer: 60,
      repRange1: "12-15",
      repRange2: "8-12",
      repRange3: "6-10",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Overhead Press - Barre",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 150,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Curl Marteau - Haltères",
      advice: "",
      timer: 90,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Hip Thrust - Barre",
      advice: 'Pic contraction 2" en haut',
      timer: 90,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Élévation frontale - Haltères",
      advice: 'Pic de contraction 2" en haut',
      timer: 90,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Curl Incliné - Haltères",
      advice: "Viser épaule avec petit doigt",
      timer: 90,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Curl Incliné - Poulie",
      advice: "",
      timer: 60,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Upper A",
    },
    {
      name: "Squat - Barre",
      advice: "",
      timer: 120,
      repRange1: "6-10",
      repRange2: "6-10",
      repRange3: "6-10",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Press",
      advice: "75kg à vide",
      timer: 120,
      repRange1: "6-10",
      repRange2: "6-10",
      repRange3: "6-10",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Leg Curl",
      advice: '30" de chaque avec Leg Extension',
      timer: 30,
      repRange1: "8-12",
      repRange2: "8-12",
      repRange3: "8-12",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Upright Row Penché",
      advice:
        "Augmenter le poids à chaque série. Dernière série dégressive AMRAP",
      timer: 60,
      repRange1: "15-20",
      repRange2: "10-15",
      repRange3: "6-10",
      repRange4: "",
      type_session: "Lower",
    },
    {
      name: "Développé assis - Haltères",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 150,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Oiseau assis - Haltères",
      advice: "Coudes perpendiculaires au corps",
      timer: 60,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Upright Row - Haltères",
      advice:
        "Augmenter le poids à chaque série. Dernière série dégressive AMRAP",
      timer: 60,
      repRange1: "12-15",
      repRange2: "8-12",
      repRange3: "6-10",
      repRange4: "",
      type_session: "Upper B",
    },
    {
      name: "Développé incliné - Barre",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 150,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Séance A",
    },
    {
      name: "Tractions lestées prise neutre",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 120,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Séance A",
    },
    {
      name: "ATG Split Squat - Haltères",
      advice: "45 secondes de chaque côté",
      timer: 45,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Séance A",
    },
    {
      name: "Upright Row - Haltères",
      advice: "",
      timer: 60,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Séance A",
    },
    {
      name: "Curl Incliné - Haltères",
      advice: "1 mega série - 10s entre chaque - 4 séries",
      timer: 10,
      repRange1: "10-15",
      repRange2: "4-6",
      repRange3: "4-6",
      repRange4: "",
      type_session: "Séance A",
    },
    {
      name: "Dips lestés",
      advice: "Top set puis -10% du poids à chaque série",
      timer: 150,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Séance B",
    },
    {
      name: "Rowing Bucheron - Haltères",
      advice:
        "Top set puis -10% du poids à chaque série - 1min de chaque côté",
      timer: 60,
      repRange1: "4-6",
      repRange2: "6-8",
      repRange3: "8-10",
      repRange4: "",
      type_session: "Séance B",
    },
    {
      name: "Romanian Deadlift - Barre",
      advice:
        "Rétraction, menton sur la clavicule et s'arreter en dessous des genoux",
      timer: 90,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Séance B",
    },
    {
      name: "Up Right Row - Haltères",
      advice: "",
      timer: 60,
      repRange1: "10-15",
      repRange2: "10-15",
      repRange3: "10-15",
      repRange4: "",
      type_session: "Séance B",
    },
    {
      name: "Extension Triceps Nuque - Haltères",
      advice: "1 mega série - 10s entre chaque - 4 séries",
      timer: 10,
      repRange1: "10-15",
      repRange2: "4-6",
      repRange3: "4-6",
      repRange4: "",
      type_session: "Séance B",
    },
  ];

module.exports = defaultExerciseTypes;